<?php

namespace Test\AbraFlexi\Acceptor;

use AbraFlexi\Acceptor\ChangesApi;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-06-21 at 09:52:50.
 */
class ChangesApiTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var ChangesApi
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new ChangesApi();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

}
