<?php

namespace Test\AbraFlexi\Acceptor\Saver;

use AbraFlexi\Acceptor\Saver\PdoSQL;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-06-21 at 09:52:49.
 */
class PdoSQLTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var PdoSQL
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new PdoSQL();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers AbraFlexi\Acceptor\Saver\PdoSQL::setCompany
     * @todo   Implement testsetCompany().
     */
    public function testsetCompany() {
        $this->assertEquals('', $this->object->setCompany());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Acceptor\Saver\PdoSQL::getLastProcessedVersion
     * @todo   Implement testgetLastProcessedVersion().
     */
    public function testgetLastProcessedVersion() {
        $this->assertEquals('', $this->object->getLastProcessedVersion());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Acceptor\Saver\PdoSQL::saveLastProcessedVersion
     * @todo   Implement testsaveLastProcessedVersion().
     */
    public function testsaveLastProcessedVersion() {
        $this->assertEquals('', $this->object->saveLastProcessedVersion());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Acceptor\Saver\PdoSQL::sqlColsToJsonCols
     * @todo   Implement testsqlColsToJsonCols().
     */
    public function testsqlColsToJsonCols() {
        $this->assertEquals('', $this->object->sqlColsToJsonCols());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Acceptor\Saver\PdoSQL::jsonColsToSQLCols
     * @todo   Implement testjsonColsToSQLCols().
     */
    public function testjsonColsToSQLCols() {
        $this->assertEquals('', $this->object->jsonColsToSQLCols());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Acceptor\Saver\PdoSQL::saveWebhookData
     * @todo   Implement testsaveWebhookData().
     */
    public function testsaveWebhookData() {
        $this->assertEquals('', $this->object->saveWebhookData());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Acceptor\Saver\PdoSQL::wipeCacheRecord
     * @todo   Implement testwipeCacheRecord().
     */
    public function testwipeCacheRecord() {
        $this->assertEquals('', $this->object->wipeCacheRecord());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Acceptor\Saver\PdoSQL::locked
     * @todo   Implement testlocked().
     */
    public function testlocked() {
        $this->assertEquals('', $this->object->locked());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

}
